heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

parameters:
  server_name:
    type: string
    description: A name for the server
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
  Net:
    type: string
    description: Network ID for the server
  VolumeName:
    type: string
    description: A name for the volume

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
      - network: { get_param: Net }
  new_volume:
    type: OS::Cinder::Volume
    properties:
      name: { get_param: VolumeName }
      size: 1
  volumeattach:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: new_volume }
      instance_uuid: { get_resource: my_instance }
